/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jeremy E. Grayson (https://sketchfab.com/JeremyGrayson)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/folding-chair-low-poly-54bd0acd7c524d678128367a25a0f504
title: Folding Chair - Low Poly
*/
import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    InEx_BrushedMetal: THREE.MeshStandardMaterial
  }
}

export function Chair(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./assets/chair/scene.gltf') as unknown as GLTFResult;

  return (
    <group {...props} dispose={null} 
    rotation={[-4, -1.5, -4]}
    position={[ 0,-1,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1.31, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.InEx_BrushedMetal}>

            </mesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./assets/chair/scene.gltf')
