/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: oisougabo (https://sketchfab.com/oisougabo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tv-set-356d85b4451f4ff4aeb04d6a3ebb1b9a
title: Tv Set
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    tvSet_lo_lambert1_0: THREE.Mesh
  }
  materials: {
    lambert1: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./assets/tv_set/tv.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} 
    scale={0.03}
    position={[-.3, 0.6, 0.5]}
    rotation={[-1.3, -3, -0.2]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.tvSet_lo_lambert1_0.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tv.gltf')
